GET http://fsopen-part2-phonebook.herokuapp.com/api/persons

###
GET http://fsopen-part2-phonebook.herokuapp.com/info

###
GET http://fsopen-part2-phonebook.herokuapp.com/api/persons/5

###
DELETE http://fsopen-part2-phonebook.herokuapp.com/api/persons/87915

###
POST http://fsopen-part2-phonebook.herokuapp.com/api/persons HTTP/1.1
content-type: application/json

{
    "name": "sdfvsmf",
    "number": "26765"
}

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/60ed3a7e308e4c2e1bfcc7e3

###
GET http://localhost:3001/api/persons/idWithBadFormat

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "ASDFGH",
    "number": "26765"
}

###
PUT http://localhost:3001/api/persons/60ee54ede074af1c3bd3eac8 HTTP/1.1
content-type: application/json

{
    "name": "zxcv",
    "number": "12334"
}