GET http://fsopen-part2-phonebook.herokuapp.com/api/persons

###
GET http://fsopen-part2-phonebook.herokuapp.com/info

###
GET http://fsopen-part2-phonebook.herokuapp.com/api/persons/5

###
DELETE http://fsopen-part2-phonebook.herokuapp.com/api/persons/87915

###
POST http://fsopen-part2-phonebook.herokuapp.com/api/persons HTTP/1.1
content-type: application/json

{
    "name": "sdfvsmf",
    "number": "26765"
}